"""Add filename to conversation messages

Revision ID: d03366a19284
Revises: 39a490743c16
Create Date: 2026-03-16 07:36:15.292516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03366a19284'
down_revision: Union[str, Sequence[str], None] = '39a490743c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('filename', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_conversation_messages_filename'), 'conversation_messages', ['filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_filename'), table_name='conversation_messages')
    op.drop_column('conversation_messages', 'filename')
    # ### end Alembic commands ###
